#!/bin/sh

DAEMON="udpserver"
PIDFILE="/var/run/$DAEMON.pid"

start() {
    printf "Starting $DAEMON: "
    start-stop-daemon -S -q -x /usr/sbin/$DAEMON -- -d
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping $DAEMON: "
    start-stop-daemon -K -q -n $DAEMON
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
        start
	;;
    stop)
	stop
	;;
    restart|reload)
	stop
	start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
